### ISSUE TITLE
String problem

### ISSUE THREAD

**Issue by hiilikewiki** [xpyctum/SignStatus#8]
So, i updated this plugin to API 2.0.0 and it all went very well, no issues at all, however, when I start the server it says an error occured and takes you through the exits and stuff like that. So i had a look at the crash dump, and as im no big coder, could only understand that there was an issue with the string.
My crash dump is attached below.

Help would be appreciated,
Archie Stride

**Comment by archiestridegmail** [comment]
[


](url)

**Comment by archiestridegmail** [comment]
It wont let me attach soz

**Comment by hiilikewiki** [comment]
Here is the crash report

Code:
[1] <?php
[2] 
[3] namespace SignStatus;
[4] 
[5] use pocketmine\nbt\tag\String;
[6] use pocketmine\scheduler\PluginTask;
[7] use pocketmine\tile\Sign;
[8] 
[9] class Task extends PluginTask{
[10]     private $plugin;
[11]     private $countable;
[12] 
[13]     public function __construct(SignStatus $plugin){
[14]         parent::__construct($plugin);
[15]         $this->plugin = $plugin;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 82; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT STRIDE-FAMLAP 10.0 build 14393 (Windows 10) AMD64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
DevTools 1.11.0 by PocketMine Team for API(s) 2.0.0
KitPro 4.1 by  for API(s) 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
SignStatus 3.0.0 by xpyctum for API(s) 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 2.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvlvIzeW/lcIdbBpL1Q6fSrrLAwfM41tt7W2Gz2YaGBQVSyJcV0psiwrQf73/d4j65DtHDPT
P2zPBK7i8c7vHWTpl57VqerNxvtH4+PD6dHxtN9TZZmXvdkvPbstMNW7fDi/uZ5/+Hj5cHl7e3Pb
6/dSZYxc0dy5zLLcisooUeTho7KpztRikS3tYmHlarG4s6XOVkIa4Z+WKpS0/Fv3/q3QRkhhChVq
mYgwkcaITEKmfi/WCfEY3ulVdmelrczD03Qwwv+KtSyHpgw7U8N7aR6xKYEAvdnBr/1ekVQrnYFA
uwjzYR4pUm6Mif/672JdYGyCZ/yZ4g+xNoUMlWh3fYe5fbfkAH/+SFlafvjGOhOuVVQlqlws5iwa
SUyLj95YbKE7CEIGWnHsuJ/gj7MQbRXq2aosMqKl9gsWjUdYJfCvKPWTtEp84wxBdMbjl3NhXmVW
LhPF094Q42m9rFomOhRxlYVW55l4eAjzzNiyCu371j41hz1mv+/38n5ZqszOZt199WJmeNBZ/I1d
axN876bFaSs3fGlLuKQ3+6H3biTe7812THWnyidVBt+HpTTriyot3i/zPFEy2+v9o99bqUyVMiGX
Y5WBFmA5HhxG6gkCLCudRL3ZCGgpc5uHORYeT/o9WWgsmxDYsGqlLd5Gf/IfNpTyMdFL2jM4ZgoV
Q3rW+6KzKN8Y8ele3N3ffri4DK7Orj+ezcUYnARLI8b705OpeF8vHY/2xNn1xeE+yBBcZ70jiDXF
28/wPl6nXkpMPuSGmHz49OkeA/yyQQg0wWDIDBfq6R4G4mcvVjPU3zHSeMyEZWXXeWnI/HO2+zXs
Lu6VTMnAbKofvK3wrjKCEwSDu1W/F6mCQIolmDN5bC+6A6nkCK35LxYdSZJcknp392e395/nGNio
pdGW5F1bW5jZcAjHrKvlIMzTYSvZsKEBvf9H23mZd1T1A11F9wfjHS2/klKO02LRcPQKzW/u7r/c
3H686KqUVUkCcedVqeaqTLvOacd2vTMdHO0653D/6mo0Ev8hwO5HFdoPWawzbbcdL8GnU/bpv6XZ
g+OEPFaL1nn8A0Xf9B3tdQAdtnRgjk7mbu2xk85bg9Rh0DHIc7ENbfXVUNoydpm5EeJPOPZOp0Wi
ziDbjibN4K5rj14g8lXcQch1vlrrsPh6ytWykHIduf7lMOxQ2THAX1VSqPJNM/iprjFIqf1dY8hE
V8n2dxWPZWJ2NO/a+nes4EgvFmsWZLG4puF/HtAyUT/KLCpzkBu2tSrwWXhoS6WGqTRWlcNX2vs0
cL6W9kUW4KFdpOy/xLwLzT8X8q+t1EbfKyP1riQ3AcYls7+pJ51XZo4K5sd7v5EgSOr26SukBybT
QOqLLItXYOLBXRi9qmVXMnnU5aP554D0ll2MvS9lZmKG7l2Sbzqvl8agBUJvC1N1LBR75mgLWeAN
BK4Dzwv/h1mFyrosoTZgVIvGvdAAzQyQZLWiDuDdvHkT5zlqwkpQZ70oF9m7azR1Z9VKTCboM2b7
x7PpiTj7OziKyWh8SEscxYCse3pRIvdY/NeZKPLSno5PxtMJDa6wLEWHfTqit1Q+A/JyC/FOJzyC
1nqTBdRrKQbNaTCm4c0aWgWJNvY0z2jA2T/4qVLldneoRCfpR+hxUKAd3uRldPqf/A9McxudUgJC
PxjbmZhfCtch0hY6rqCZVV6sQIZrrZ5UChcZT1UmcGAQJ3q1hjRx3IotM53Cj36dG0vzZT0Q5yUI
NxbwW3FSicK8bN6Lp8Kvj3Qc67BK7PaUjeA6VZuXgVHW4iBhTmk4gXyJsz/0TKJ2zCgVdZbQce30
4vLq7PPHe1aksnlg5JPy/KhFbFLRYJsmhA1BGU6EDIsK3KnLJ3QIaCPaZB5cz4EWcb9WOKfU4gl0
98KulcgzQMsiKkXozoNLJXQWJlWkIjyIV6gkWnd5ip0xEXhJ08hY9UWOmdIQSbEE8B7FNq9KT0vo
WMDKOtbMAQYuAShkbhD+pDYNuWGkYgkTG7HJs2+tkEWhZCnINCmUDeHsLcQXdPRwem/WKhNVsSpl
BAKDRUZId8Rmi0y8u18jdwcJhiBFIrNVhZOwoFMlm8xHhdF4T3LQ1z+zUWnr+VqFXovdjRCgTnsq
G2z0oy5UpOUgL1dDeht+RGQ85PHDh7ubh8PpSTB5oH0wY0NoJhZIWqtFjxh9WSuynbA55MkiAS2F
4bMp3ESpKcHZL3LTbE2WFHLgSVl2KY5HGofgNapYwk5OQdghvGXJyRHjZl1ZnFUQDe5igIRxMYcD
fW5U5MQ6o8gSFOV0EeBroXjSUvwvxTmWcLzXVXImqH2hjXdr7JOEUoODnfBcnKukJ0R3EAZiFwAC
a3c2/4CVyPYR2amdCCDWEkK15C85s9R0oLGggMUZOQci+M5iKzyOsNznoWa2NcO7LxqGzjNASkaR
KJVxyCMxgbVHiCMN6hdlG7r2WCqyB4yufqpkQu5Y6SesfZJJpcR7zxKZeA/EHT/kP0UZN4A3VytV
zjBLnD9V6RLWRjidmW0W8vUAssUjAmhA85/hBMZnrSStWpc5siEggdWmLzi7CJ+FANk+zJDCaoZK
KJsF5YfG0ipD5NASpn3HkKFrnAJCPiNHWgUTQB2GetaIRlZ14nyIKUJpCUViX2j7LSxnS94VKSoO
jMIXe8V7aEA3JROyCOsQeC1nTImildJvueVY/UuSL2FYqtfCDQN9qbaUk1K1ksuthUDizokyYuba
kHtdpEOnjWbB2NiCCoOjU9vfsF1iDbggTSENZ0wqRo6oOTr3Q5mKQbvKoUdOoUE2A58VCxmwYDMx
WnCq4KxskWpk9P9cfOpnfkd4Kn//lvDG5gXz96mqkcdTMwIhRU0AsoyXhnjWIo1Hk30nFdpanXM5
olg0xDDkhOyla+JtDFZINRFhjFcEiAflIo3TeI5+LkOEwm6UHX7LrM6caG0SzvAU627Zggsu0UD0
tZHs0hFxuKEUQhWOlw9eLya1fYsKE9Ldaay5BCtBsjobu72NArCkKkyr5nTk9TR7bwrktZ46rVey
XML/QZgniWvdKMLetCrDiUTxe4Tfg9hNZVZxye1KgXakAhb2+nVOeAEGjwaXV+O4zg1pi7KBuHH1
jt+AiHVeJVEjiEYG2WSiFZ1wKwqWHAoejkZOR/HuiiPhVW5krLjdjVJxmad1iqW9fj7oZqWOT6GE
d91LKLyBn84+aqHDdZU9Gmfvj4x6Sog8SJLROYG0Ea6n7XN4lmhAjFsUUA9AvUxLi0jVbvaBcnLo
5bzI3baX7qMiQJ2S29al4Lj4ZV9BZy5EQYjeXDmtPRZqRjTRVO/fJbXIMmXJF03rBmgkrhIupUXz
T42IpC4XBRB48lmJA9A1pn7WJaOlamoip5t33fRVz1Dgl1tLtPsiGHfATLWP2Qa2FgVp5eDQZZW2
1nI/T4UucunOO9DtxaCXaSD+ikMKzHuKXhjAPZ9/7mMvJFgi/2x0ZNcua3N8N+QDJj8TR74xaFsG
w4bpLB2IswjxtJZJPEST77qYSAFnnhFYOvzlWTcgm+rcodXpky6fKfioDZJJ3wU2MfY33gMB2CiG
NtX6z/NsXncKbc9OTRBtwrmZuFVFVgT+tduT4ZSlltXKuT/3OVNQtSgZ0OpZhZVrdij50I36oJk1
hAjuYYp1MdCZJjHGvn/5Xoypb/FFihpU5lQ3p7yX0pRvWhfeqzNHwLWcRgwN3yH2xXAVOi8hRUam
I3991Ns5gqi6HyUTwCju8MVLPVLJcoydEP6wDFa/JXBbZiLF1MofTaAQ3xWSuEAv8M75Te7QRxKm
w53tsIdB7GtpONwZBe8+3dxfzgQncPw/rEr6IAT/ESG+7CAUsHiecyNeg5azHceHOJIgKXldGZBc
3SAJAdASCCcjX40oK7oiR4ik8zCN+8rmE8jucJ0OXVt9R5FPCi6lUR1m78eIuTe49MUEE+O3JpQN
B3sc/0Z1pWA43BNlOqX52xKhkOMcP+oinCf5PNwelCmn8IGKGjHKLDLZyK1xtD2dDo52SgHD6Cyl
b3+dWmJ8+1cLQeITNTp9IM3T40zs//ZWWWI0crI7GrsFTIxPJm/uZnRlyh1Jl8pRW6qYkhpfs1Dy
Izc0VN3lSyeLuiR6J58UfU1GdqGTt6KTXLH1twy+rDW9EeecmC9h6wzrM2JcJbwsN4BqQCGqQ1eV
+DRX0tEewADZ2lQ/5nSocrFhZEpYSTntUq1q9H/hDDJo7Yxr+SzkS7vgOBVyqWnxsOsLBumtjHRl
Otu8H6SXjoPUbfW4o/VofCgn0S1XUBURsNgKiFO7ko4JX8q1BdUJ3p4Ra9kHr4X3+W8jNR/3cbSv
lPev389hz+OBgbNm4vhfolbkRZV4av6ZqtwLwouMYzKA9Uhod5cXMI4MWZJMmdJHarq98aNjnx7o
Em0mXJ9Yu5Q+MFcF+ibXPDpAcvJwPYunBSpHtMszJKIH9LqRxKgZ5DGZLjV9Lucl/v7OHfdnLhnR
zQR95BZu1JVrDxKHXn8oaJIb4Tqgu6Ldkaac7IyiyukszlsYrHPyPbMcdK4O0VOxfFmebVM6MXCE
GNjXNILSEchPi3aaBQbWpJCrFaqPv2dobnCo3aRP/Y9va+PkIXLmLXnIXg7K7OKXu4EJNztzDiiz
wBfntpnk0bzo3D2d0/Uj34epJC+oWvXxDg3oss/WXR2anBhNt4KxUZ8yqvO0yJfWyvBvYLpEhP80
0ekhKvSuxroCVyc8T4085KZr+uaFUTabzVsmSTTKjfPK5bOkeuteqGEBfS/ErJaGpwB2OnTPxA/0
GKDI9PkU/g+i6LJg3YZ0L25Zifro4c5/9YU291Zv3QPzOZmrmOGOgdRO0UhoCOpLfEd05soC8JOg
+28KXS5JLbeZuPp4dj+bfHfUPzh5Hvenz9P+5LvxdxEqscta7+n7G//y5fR4JFbAt3Fv+wd7fE/O
v6wx/FFr9kvvHHWo87OLZYhuZN0ZoLvTLJJld8j/dqp+J9h1XmOdWNVdv0aI8fc8+kalqRXqTP5o
dj72oW/bFrYzfzf/2Hkrwh1pb1XsT2+dQeNa8u6IlaRC1BlKt+anhH9h4p/EAWbGkwAwFgF9IDoY
7Y+O8PjNB/ghPjhRy6PDo1iNj+Th4dHJwfHJ8iAcHR1GJ7E8Po6m0T7K2Eh8A9o2f1QZUnPXBj/r
wv3qxH2u/Nn9gqaexdszf7JoTJqn9F1vNJqOx5MTDMwvbjrT8zU7hL7oTXr1t8K/XXcttUtvE0XP
u5N0ktmREGObUu967ouSjwh+/q3PlFmhyU1emlF3TY1Xq6a84yhwv0MyHLqmu23pbuw7Q1vJAvNH
yttz+vFH4W88+OcP48Eh/74tfYhyiwTQ2bnq+vXvVEdu5lzH/PAhiXF12fv11/8DGKe1/Q==
===END CRASH DUMP===

**Comment by xpyctum** [comment]
Please, use StringTag, not String.

**Comment by hiilikewiki** [comment]
So do I change that in the src?

**Comment by xpyctum** [comment]
@archiestridegmail You can download plugin from here. I also edit repo.

**Comment by hiilikewiki** [comment]
Thanks, I will close issue.
